### ISSUE TITLE
Implement WebSockets for comments

### ISSUE THREAD

**Issue by aseiden** [TrendGame/UforU#35]
# Tasks
- [x] Render comments list on college page on load from the DB
- [x] Capture user input to component state 
- [x] Submit handler to emit socket event and send data to server
- [x] Server socket listener for new message to write message to DB
- [x] On DB write complete, socket broadcast to all clients with comments table

**Comment by epan** [comment]
Related PRs:

1. https://github.com/TrendGame/UforU/pull/39
1. https://github.com/TrendGame/UforU/pull/40
1. https://github.com/TrendGame/UforU/pull/42
1. https://github.com/TrendGame/UforU/pull/43
1. https://github.com/TrendGame/UforU/pull/45/
